#!/bin/sh

# below only installed to show how to add Python packages into the container
# RUN echo nameserver 8.8.8.8 > /etc/resolv.conf && 
#pip install --no-cache -r requirements.txt

python -u blend-to-unity.py
